sudo: required
dist: trusty
language: cpp
env: GCC_VERSION=5 CPP=11
addons:
  apt:
    packages:
      - g++-5
      - libsecret-1-dev
      - qt-latest
    sources:
      - ubuntu-toolchain-r-test
      - beineri/opt-qt57-trusty
before_install:
  - source /opt/qt57/bin/qt57-env.sh
script:
  - mkdir build
  - cd build
  - cmake .. && make
